algoritmo "ParOuImparProcedimento"
var
   N: inteiro
   Procedimento parouimpar (V: Inteiro)
   inicio
         Se (V%2=0) entao
            Escreval("O numero ", V, " é PAR")
         senao
              Escreval ("O numero ", V, " é IMPAR")
         FimSe
  Fimprocedimento
inicio
      Escreva("Digite um numero: ")
      Leia (N)
      parouimpar(N)
       Escreval("O valor de V e ", V)
         Escreval ("O valor de N e ", N)
 fimalgoritmo
